### ISSUE TITLE
Oracle Image use already available one?

### ISSUE THREAD

**Issue by melloware** [asman1337/kafka-debezium-oracle-docker-setup#1]
Instead of building your own image can you just make this work with one of GVenzels Oracle Free images: https://github.com/gvenzl/oci-oracle-free

For  example I use his Oracle 23 Free image.

```
services:
  oracle:
    image: gvenzl/oracle-free:slim-faststart
    environment:
      - ORACLE_PASSWORD=Passw0rd
      - APP_USER=quarkus
      - APP_USER_PASSWORD=quarkus
    ports:
      - "1521:1521"
```

This creates a single PDB with the name `FREEDB1` and automatically creates the APP_USER and APP_PASSWORD.

Part 2.

If you can update to use that can you update your script to make it work with this?  I tried to modify your script but couldn't get it to work right and would appreciate the help.  THe APP_USER above in this case QUARKUS cannot see `SELECT * FROM v$logmnr_contents;` as QUARKUS user.

**Comment by melloware** [comment]
Or use Oracles Offical image?

```yml
version: "3.8"

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    restart: unless-stopped
    ports:
      - "1521:1521"   # Oracle Listener
      - "5500:5500"   # EM Express (if enabled)
    environment:
      ORACLE_PWD: "oracle" # Initial SYS/SYSTEM password
      ORACLE_SID: "FREE"
      ENABLE_ARCHIVELOG: "true"
    volumes:
      - oracle-data:/opt/oracle/oradata # Persistent storage for database
   ```
